<?php

// Front Controller

// 1. Load Composer's autoloader
// This will be generated by running `composer install`
require_once __DIR__ . '/../vendor/autoload.php';

// 2. Simple Routing
use EduFlex\Controllers\SuperAdmin\AuthController;

$request_uri = $_SERVER['REQUEST_URI'];
$base_path = ''; // If the app is in a subdirectory, change this

use EduFlex\Controllers\OrderController;

// Simple router
$route = str_replace($base_path, '', $request_uri);
$route = trim($route, '/');
$route = strtok($route, '?'); // Remove query string

switch ($route) {
    case 'order':
        $controller = new OrderController();
        $controller->showOrderForm();
        break;

    case 'api/domain-check':
        $controller = new OrderController();
        $controller->checkDomain();
        break;

    case '':
    case 'home':
        require_once __DIR__ . '/../views/landing.php';
        break;

    case 'super-admin/login':
        $controller = new AuthController();
        $controller->showLoginForm();
        break;

    case 'super-admin/login/submit':
        $controller = new AuthController();
        $controller->login();
        break;

    case 'super-admin/dashboard':
        $controller = new AuthController();
        $controller->dashboard();
        break;

    case 'super-admin/logout':
        $controller = new AuthController();
        $controller->logout();
        break;

    default:
        http_response_code(404);
        echo "404 Not Found";
        break;
}
