<?php

// --- DEBUGGING: TEMPORARILY ENABLE ERROR REPORTING ---
// This should be removed in a production environment.
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
// --- END DEBUGGING ---

// Front Controller

// 1. Load Composer's autoloader
// This will be generated by running `composer install`
require_once __DIR__ . '/../vendor/autoload.php';

// 2. Simple Routing
use EduFlex\Controllers\SuperAdmin\AuthController;
use EduFlex\Controllers\SuperAdmin\SchoolController;
use EduFlex\Controllers\SuperAdmin\TransactionController;

$request_uri = $_SERVER['REQUEST_URI'];
$base_path = ''; // If the app is in a subdirectory, change this

use EduFlex\Controllers\OrderController;
use EduFlex\Controllers\WebhookController;

// Simple router
$route = parse_url($request_uri, PHP_URL_PATH) ?? '';
$route = trim($route, '/');

switch ($route) {
    case 'order':
        $controller = new OrderController();
        $controller->showOrderForm();
        break;

    case 'order/submit':
        $controller = new OrderController();
        $controller->processOrder();
        break;

    case 'api/domain-check':
        $controller = new OrderController();
        $controller->checkDomain();
        break;

    case 'webhooks/whmcs':
        $controller = new WebhookController();
        $controller->handleWhmcs();
        break;

    case '':
    case 'home':
        require_once __DIR__ . '/../views/landing.php';
        break;

    case 'super-admin/login':
        $controller = new AuthController();
        $controller->showLoginForm();
        break;

    case 'super-admin/login/submit':
        $controller = new AuthController();
        $controller->login();
        break;

    case 'super-admin/dashboard':
        $controller = new AuthController();
        $controller->dashboard();
        break;

    case 'super-admin/transactions':
        $controller = new TransactionController();
        $controller->index();
        break;

    case 'super-admin/schools/create':
        $controller = new SchoolController();
        $controller->create();
        break;

    case 'super-admin/schools/store':
        $controller = new SchoolController();
        $controller->store();
        break;

    case 'super-admin/schools/edit':
        $controller = new SchoolController();
        $controller->edit();
        break;

    case 'super-admin/schools/update':
        $controller = new SchoolController();
        $controller->update();
        break;

    case 'super-admin/schools/delete':
        $controller = new SchoolController();
        $controller->destroy();
        break;

    case 'super-admin/schools/approve':
        $controller = new SchoolController();
        $controller->approve();
        break;

    case 'super-admin/logout':
        $controller = new AuthController();
        $controller->logout();
        break;

    default:
        http_response_code(404);
        echo "404 Not Found";
        break;
}
